title: "Valter Mariano Sociedade Individual de Advocacia"
description: "Advocacia criminal. Conteúdo jurídico informativo e atualização jurisprudencial."
baseurl: ""
url: "https://valtermarianoadvocacia.github.io"

permalink: /blog/:title/
markdown: kramdown
lang: "pt-BR"
